config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "root#index"

  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response

  resources :line_reports, only: %i[index show]
  resources :annual_leave_requests, only: %i[new create] do
    get "approve"
    patch "update_status"
    get "deny"
  end
  get "/annual_leave_requests/check", to: "annual_leave_requests#check", as: "check_annual_leave_request"
  get "/annual_leave_requests/confirmation", to: "annual_leave_requests#confirm", as: "annual_leave_request_confirmation"
  get "/annual_leave_requests/approval_confirmation", to: "annual_leave_requests#confirm_approval", as: "confirm_annual_leave_request_approval"
  get "/annual_leave_requests/denial_confirmation", to: "annual_leave_requests#confirm_denial", as: "confirm_annual_leave_request_denial"

  mount GovukPublishingComponents::Engine, at: "/component-guide" if Rails.env.development?
end

app/models/annual_leave_request.rb
class AnnualLeaveRequest < ApplicationRecord
  belongs_to :user

  validates :date_from, :date_to, :days_required, presence: true
  validates :date_from, comparison: { less_than_or_equal_to: :date_to, message: "must be the same as or before Date to" }
  validates :date_from, :date_to, comparison: { greater_than: Time.zone.today, message: "must be in the future" }
  validate :user_has_enough_annual_leave_remaining
  validates :confirm_approval, acceptance: { accept: "confirmed" }
  validates :denial_reason, presence: true, allow_nil: true

private

  def user_has_enough_annual_leave_remaining
    if user.annual_leave_remaining < days_required
      errors.add(
        :days_required,
        message: "exceeds remaining annual leave. You have #{user.annual_leave_remaining} days annual leave remaining",
      )
    end
  end
end

app/controllers/annual_leave_requests_controller.rb
require "status_update"

class AnnualLeaveRequestsController < ApplicationController
  def new
    @annual_leave_request = AnnualLeaveRequest.new
  end

  def check
    @date_from = format_date_params(check_leave_request_params[:date_from])
    @date_to = format_date_params(check_leave_request_params[:date_to])
    @days_required = WorkingDaysCalculator.new(@date_from, @date_to).number_of_working_days
  end

  def create
    @annual_leave_request = current_user.annual_leave_requests.build(annual_leave_request_params)

    if @annual_leave_request.save
      @email_response_notification = notify_client.send_email(new_request_email_hash)
      redirect_to annual_leave_request_confirmation_path
    else
      render "new"
    end
  end

  def confirm; end

  def approve
    line_reports_leave_requests = AnnualLeaveRequest.where(user: current_user.line_reports)
    @annual_leave_request = line_reports_leave_requests.find(params[:annual_leave_request_id])
  end

  def deny
    line_reports_leave_requests = AnnualLeaveRequest.where(user: current_user.line_reports)
    @annual_leave_request = line_reports_leave_requests.find(params[:annual_leave_request_id])
  end

  def update_status
    line_reports_leave_requests = AnnualLeaveRequest.where(user: current_user.line_reports)
    @annual_leave_request = line_reports_leave_requests.find(params[:annual_leave_request_id])

    if @annual_leave_request.update(annual_leave_request_params)
      @email_response_notification = notify_client.send_email(status_update.email_hash)
      redirect_to status_update.confirmation_page_path
    else
      render status_update.action
    end
  end

  def confirm_approval; end

  def confirm_denial; end

private

  def format_date_params(date)
    "#{date[:day]}/#{date[:month]}/#{date[:year]}".to_date
  end

  def check_leave_request_params
    params.require(:annual_leave_request).permit(date_from: %i[day month year], date_to: %i[day month year])
  end

  def annual_leave_request_params
    params.require(:annual_leave_request).permit(:date_from, :date_to, :days_required, :status, :confirm_approval, :denial_reason)
  end

  def status_update
    case @annual_leave_request.status
    when "approved"
      ApprovedStatusUpdate
    when "denied"
      DeniedStatusUpdate
    end.new(@annual_leave_request)
  end

  def new_request_email_hash
    {
      email_address: line_manager.email,
      template_id: "1587d50b-c12e-4698-b10e-cf414de26f36",
      personalisation: {
        line_manager_name: "#{line_manager.given_name} #{line_manager.family_name}",
        name: "#{user.given_name} #{user.family_name}",
        date_from: @annual_leave_request.date_from.to_fs(:rfc822),
        date_to: @annual_leave_request.date_to.to_fs(:rfc822),
        days_required: @annual_leave_request.days_required,
      },
    }
  end

  def notify_client
    @notify_client ||= Notifications::Client.new(ENV["NOTIFY_API_KEY"])
  end

  def line_manager
    @annual_leave_request.user.line_manager
  end

  def user
    @annual_leave_request.user
  end
end

app/views/annual_leave_requests/approve.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= render "govuk_publishing_components/components/back_link", {
      href: "javascript:window.history.back()"
    } %>

    <% if @annual_leave_request.errors.any? %>
      <%= render "govuk_publishing_components/components/error_summary", {
        title: "There was a problem with your approval",
        description: "Fix the following issue(s) and re-submit your request",
        items: error_messages_for(@annual_leave_request)
      } %>
    <% end %>

    <%= render "govuk_publishing_components/components/title", {
      title: "Approve annual leave request",
      average_title_length: "long",
    } %>

    <% if @annual_leave_request.errors.any? %>
      <%= render "govuk_publishing_components/components/error_summary", {
        title: "There was a problem with your approval",
        description: "Fix the following issue(s) and re-submit your response",
        items: error_messages_for(@annual_leave_request)
      } %>
    <% end %>

    <%= form_with url: annual_leave_request_update_status_path(@annual_leave_request), method: :patch do |f| %>
      <%= hidden_field(:annual_leave_request, :status, value: "approved") %>
      <%= hidden_field(:annual_leave_request, :confirm_approval, value: "unconfirmed") %>
      <%= render "govuk_publishing_components/components/checkboxes", {
        name: "annual_leave_request[confirm_approval]",
        heading: "Confirm you approval",
        visually_hide_heading: true,
        hint_text: "Check the box below to confirm your approval",
        error: error_message_for_input(@annual_leave_request.errors, :confirm_approval),
        items: [
          {
            label: "I confirm my approval",
            value: "confirmed"
          }
        ]
      } %>

      <%= render "govuk_publishing_components/components/button", {
        text: "Approve leave"
      } %>
    <% end %>
  </div>
</div>

app/views/annual_leave_requests/check.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= render "govuk_publishing_components/components/back_link", {
      href: "javascript:window.history.back()"
    } %>

    <%= render "govuk_publishing_components/components/title", {
      title: "Check your dates before requesting annual leave",
      average_title_length: "long",
    } %>

    <%= render "govuk_publishing_components/components/summary_list", {
      items: [
        {
          field: "Date from",
          value: @date_from.to_fs(:rfc822),
          edit: {
            href: "javascript:window.history.back()"
          }
        },
        {
          field: "Date to",
          value: @date_to.to_fs(:rfc822),
          edit: {
            href: "javascript:window.history.back()"
          }
        },
        {
          field: "Total annual leave",
          value: "#{@days_required} days"
        }
      ]
    } %>

    <%= form_with url: "/annual_leave_requests", method: :post do %>
      <%= hidden_field(:annual_leave_request, :date_from, value: @date_from) %>
      <%= hidden_field(:annual_leave_request, :date_to, value: @date_to) %>
      <%= hidden_field(:annual_leave_request, :days_required, value: @days_required) %>
      <%= render "govuk_publishing_components/components/button", {
        text: "Send request"
      } %>
    <% end %>
  </div>
</div>

app/views/annual_leave_requests/confirm.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= render "govuk_publishing_components/components/panel", {
      title: "Request sent",
      description: "You can now view the request status on your dashboard"
    } %>

    <%= render "govuk_publishing_components/components/heading", {
      text: "What happens next?",
      padding: true
    } %>

    <p class="govuk-body"> 
      We've sent your request via email to your line manager 
      <%= "(#{current_user.line_manager.given_name} #{current_user.line_manager.family_name})" if current_user.line_manager %> and 
      delivery manager 
      <% # TODO: Interpolate delivery manager's name %>
      for approval.
    </p>

    <p class="govuk-body">
      Your dashboard will be updated and you will receive an email when they 
      have responded to your request.
    </p>

    <%= link_to "Go to your dashboard", root_path, html_options = { class: "govuk-link" }%>
  </div>
</div>

app/views/annual_leave_requests/confirm_approval.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= render "govuk_publishing_components/components/panel", {
      title: "Annual leave request approved",
      description: "The status will be automatically updated for your line report"
    } %>

    <%= render "govuk_publishing_components/components/heading", {
      text: "What happens next?",
      padding: true
    } %>

    <p class="govuk-body"> 
      Your line report will be notified of your response via email and their request 
      status will be updated on their dashboard.
    </p>

    <%= render "govuk_publishing_components/components/heading", {
      text: "If you didn't mean to approve this request",
      padding: true
    } %>

    <p class="govuk-body">
      If you have approved this request in error, please contact an administrator
      immediately.
    </p>
    <p class="govuk-body">
      Administrators can be contacted via email (admins-holiday-logger@digital.cabinet-office.gov.uk)
      or on the #holiday-logger Slack channel
    </p>

    <%= link_to "Go back to line report dashboard", line_reports_path, html_options = { class: "govuk-link" }%>
  </div>
</div>

app/views/annual_leave_requests/confirm_denial.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <div class="govuk-panel" style="background-color: #d4351c">
      <h1 class="govuk-panel__title" style="color: white">
        Annual leave request denied
      </h1>
      <div class="govuk-panel__body" style="color: white">
        The status will be automatically updated for your line report
      </div>
    </div>

    <%= render "govuk_publishing_components/components/heading", {
      text: "What happens next?",
      padding: true
    } %>

    <p class="govuk-body"> 
      Your line report will be notified of your response via email and their request 
      status will be updated on their dashboard.
    </p>

    <%= render "govuk_publishing_components/components/heading", {
      text: "If you didn't mean to deny this request",
      padding: true
    } %>

    <p class="govuk-body">
      If you have denied this request in error, please contact an administrator
      immediately.
    </p>
    <p class="govuk-body">
      Administrators can be contacted via email (admins-holiday-logger@digital.cabinet-office.gov.uk)
      or on the #holiday-logger Slack channel
    </p>

    <%= link_to "Go back to line report dashboard", line_reports_path, html_options = { class: "govuk-link" }%>
  </div>
</div>

app/views/annual_leave_requests/deny.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= render "govuk_publishing_components/components/back_link", {
      href: "javascript:window.history.back()"
    } %>

    <%= render "govuk_publishing_components/components/title", {
      title: "Deny annual leave request",
      average_title_length: "long",
    } %>

    <% if @annual_leave_request.errors.any? %>
      <%= render "govuk_publishing_components/components/error_summary", {
        title: "There was a problem with your denial",
        description: "Fix the following issue(s) and re-submit your response",
        items: error_messages_for(@annual_leave_request)
      } %>
    <% end %>

    <%= form_with url: annual_leave_request_update_status_path(@annual_leave_request), method: :patch do |f| %>
      <%= hidden_field(:annual_leave_request, :status, value: "denied") %>
      <%= render "govuk_publishing_components/components/input", {
        label: {
          text: "Please write the reason for denying this annual leave in the box below."
        },
        name: "annual_leave_request[denial_reason]",
        error_message: error_message_for_input(@annual_leave_request.errors, :denial_reason),
      } %>

      <%= render "govuk_publishing_components/components/button", {
        text: "Deny leave",
        destructive: true
      } %>
    <% end %>
  </div>
</div>

app/views/annual_leave_requests/new.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= render "govuk_publishing_components/components/back_link", {
      href: "javascript:window.history.back()"
    } %>

    <% if @annual_leave_request.errors.any? %>
      <%= render "govuk_publishing_components/components/error_summary", {
        title: "There was a problem with your annual leave request",
        description: "Fix the following issue(s) and re-submit your request",
        items: error_messages_for(@annual_leave_request)
      } %>
    <% end %>

    <%= render "govuk_publishing_components/components/title", {
      title: "Request annual leave",
      average_title_length: "long",
    } %>

    <%= form_with url: check_annual_leave_request_path, method: :get do %>
      <%= render "govuk_publishing_components/components/label", {
        text: "Date from:",
        html_for: "annual_leave_request[date_from]",
        heading_size: "s"
      } %>

      <%= render "govuk_publishing_components/components/date_input", {
        name: "annual_leave_request[date_from]",
        hint: "For example, 31 3 2023. Dates are inclusive.",
        items: [
          {
            name: "day",
            width: 2,
            value: @annual_leave_request.date_from&.day
          },
          {
            name: "month",
            width: 2,
            value: @annual_leave_request.date_from&.month
          },
          {
            name: "year",
            width: 4,
            value: @annual_leave_request.date_from&.year
          }
        ],
        error_message: error_message_for_input(@annual_leave_request.errors, :date_from)
      } %>

      <%= render "govuk_publishing_components/components/label", {
        text: "Date to:",
        html_for: "annual_leave_request[date_to]",
        heading_size: "s"
      } %>

      <%= render "govuk_publishing_components/components/date_input", {
        name: "annual_leave_request[date_to]",
        hint: "For example, 31 3 2023. Dates are inclusive.",
        items: [
          {
            name: "day",
            width: 2,
            value: @annual_leave_request.date_to&.day
          },
          {
            name: "month",
            width: 2,
            value: @annual_leave_request.date_to&.month
          },
          {
            name: "year",
            width: 4,
            value: @annual_leave_request.date_to&.year
          }
        ],
        error_message: error_message_for_input(@annual_leave_request.errors, :date_to)
      } %>

      <%= render "govuk_publishing_components/components/button", {
        text: "Continue"
      } %>
    <% end %>
  </div>
</div>