config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "root#index"

  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response

  resources :line_reports, only: %i[index show]
  resources :annual_leave_requests, only: %i[new create] do
    get "approve"
    patch "update_status"
    get "deny"
  end
  get "/annual_leave_requests/check", to: "annual_leave_requests#check", as: "check_annual_leave_request"
  get "/annual_leave_requests/confirmation", to: "annual_leave_requests#confirm", as: "annual_leave_request_confirmation"
  get "/annual_leave_requests/approval_confirmation", to: "annual_leave_requests#confirm_approval", as: "confirm_annual_leave_request_approval"
  get "/annual_leave_requests/denial_confirmation", to: "annual_leave_requests#confirm_denial", as: "confirm_annual_leave_request_denial"

  mount GovukPublishingComponents::Engine, at: "/component-guide" if Rails.env.development?
end

app/controllers/line_reports_controller.rb
class LineReportsController < ApplicationController
  before_action :redirect_if_user_not_line_manager

  def index
    @line_reports = current_user.line_reports
  end

  def show
    @line_report = User.find_by_id(params[:id])
    @annual_leave_requests = @line_report.annual_leave_requests

    redirect_to root_path if current_user != @line_report.line_manager
  end

private

  def redirect_if_user_not_line_manager
    redirect_to root_path unless current_user.is_line_manager?
  end
end

app/helpers/line_reports_helper.rb
module LineReportsHelper
  def line_reports_table_rows(line_reports)
    rows = []

    line_reports.each do |line_report|
      rows << [
        {
          text: "#{line_report.given_name} #{line_report.family_name}",
        },
        {
          text: line_report_status(line_report),
        },
        {
          text: sanitize(link_to("Manage requests", line_report_path(line_report), { class: "govuk-link" })),
        },
      ]
    end

    rows
  end

  def line_report_status(user)
    if user.annual_leave_requests.where(status: "pending").any?
      sanitize("<strong class='govuk-tag govuk-tag--red'> Pending requests </strong>")
    else
      sanitize("<strong class='govuk-tag govuk-tag--green'> No pending requests </strong>")
    end
  end
end

app/views/line_reports/_approve_or_deny_links.html.erb
<li class="govuk-summary-card__action">
  <a class="govuk-link" href=<%= annual_leave_request_approve_path(annual_leave_request) %>>
    Approve
    <span class="govuk-visually-hidden">
      <%= annual_leave_request.status %> annual leave request from 
      <%= annual_leave_request.date_from %> to <%= annual_leave_request.date_to %>
    </span>
  </a>
  </li>
  <li class="govuk-summary-card__action">
  <a class="govuk-link" href=<%= annual_leave_request_deny_path(annual_leave_request)%>>
    Deny
    <span class="govuk-visually-hidden">
      <%= annual_leave_request.status %> annual leave request from 
      <%= annual_leave_request.date_from %> to <%= annual_leave_request.date_to %>
    </span>
  </a>
</li>

app/views/line_reports/index.html.erb
<%= render "govuk_publishing_components/components/title", {
    title: "#{current_user.given_name} #{current_user.family_name}'s Line Reports",
    average_title_length: "long",
    margin_top: 0
  } %>

<%= render "govuk_publishing_components/components/table", {
  head: [
    {
      text: "Line Report"
    },
    {
      text: "Status"
    },
    {
      text: ""
    }
  ],
  rows: line_reports_table_rows(@line_reports)
} %>

app/views/line_reports/show.html.erb
<%= render "govuk_publishing_components/components/back_link", {
  href: "javascript:window.history.back()"
} %>

<%= render "govuk_publishing_components/components/title", {
  title: "#{@line_report.given_name} #{@line_report.family_name}'s Requests",
  average_title_length: "long",
} %>

<% if @annual_leave_requests.any? %>
  <% @annual_leave_requests.each do |annual_leave_request| %>
    <%= render "shared/annual_leave_request_card", card_links: "line_reports/approve_or_deny_links", annual_leave_request: %>
  <% end %>
<% else %>
  <p class="govuk-body"> No pending annual leave requests. </p>
<% end %>